### ISSUE TITLE
Kernel compilation error

### ISSUE THREAD

**Issue by x893** [bouffalolab/bl808_linux#14]
Hello,
after run all curls ...
i run switch_to_m1sdock.sh and
`
./build opensbi   OK

./build kernel_config (nothing chane)  OK

./build kernel
...
 YACC    scripts/dtc/dtc-parser.tab.[ch]
Makefile:67: /home/mitek/bl808_linux/linux-5.10.4-808/tools/build/Makefile.include: No such file or directory
make[2]: *** No rule to make target '/home/mitek/bl808_linux/linux-5.10.4-808/tools/build/Makefile.include'.  Stop.
make[1]: *** [Makefile:71: bpf/resolve_btfids] Error 2
make: *** [Makefile:1931: tools/bpf/resolve_btfids] Error 2
`
Can you help me to resolve ?

Thanks in advance

**Comment by pinecat** [comment]
I had this same issue when trying to compile in Fedora Linux 36.  I setup an Ubuntu 20.04 VM, and the compile went off without a hitch.  Not sure precisely what the issue is, though.

**Comment by x893** [comment]
I use Ubuntu 21, I'll try Ubuntu 20. Thanks

**Comment by gamelaster** [comment]
For me, build worked just fine on Manjaro with latest packages.

**Comment by x893** [comment]
Works fine on Ubuntu 20
