### ISSUE TITLE
creating a folder or file

### ISSUE THREAD

**Issue by jonathancagua** [bouffalolab/bl808_linux#15]
I have problems creating a file, I get the following message.

[@Linux root]#mkdir jc
mkdir: can't create directory 'jc': Read-only file system
[@Linux root]#

**Comment by gamelaster** [comment]
The rootfs is squashfs, it is read only in RAM, you can't write to it. (But you can use tmpfs to do modifications, but they will stay only in RAM)

**Comment by jonathancagua** [comment]
I was able to create a file but it would be in the volatile. 

`
[@Linux root]#cd /var/volatile
[@Linux volatile]#cat > test2.sh
# !/bin/bash
echo "hola mundo"
[@Linux volatile]#cat test2.sh
# !/bin/bash
echo "hola mundo"
[@Linux volatile]#sh test2.sh
hola mundo
[@Linux volatile]#
`
 Is there any way to save it permanently? Since I want to do driver test and then add with:
`sudo insmod hello_world.ko`
