### ISSUE TITLE
Compatibility with Ox64

### ISSUE THREAD

**Issue by dewgenenny** [bouffalolab/bl808_linux#24]
Hey. Apologies if this is a stupid question.

First of all - is this software compatible with Pine Ox64 boards?

I have managed to follow the instructions and flash all parts of the built software to my Pine Ox64, however I am unsure where the console is outputting to - I have tried all the TX/RX combinations listed on this graphic https://wiki.pine64.org/images/2/24/Ox64_pinout.png with no joy.

Thanks thanks thanks for your answer

**Comment by Pavlos1** [comment]
Make sure to run `switch_to_m1sdock.sh` before building, as the (D0) UART pins are inaccessible otherwise.

Your console will then be on TX=GPIO16, RX=GPIO17.

**Comment by dewgenenny** [comment]
Yep that helped, thank you.
