### ISSUE TITLE
[Question] Does such a Linux support a command line?

### ISSUE THREAD

**Issue by illantalex** [bouffalolab/bl808_linux#26]
I just got a Sipeed Maix M1s board and flashed Linux to it according to this instruction.  All I got from the standard USB serial port was:
"dynamic memory init success,heap size = 156 Kbyte 
E907 start...
mtimer clk:1000000
psram clk init ok!"
Is there a possibility to use a command line with such a compact version of Linux? Thank you in advance for your help

**Comment by gamelaster** [comment]
Use OpenBouffalo instead, of course you can use command line, it just seems your board fails to boot.

**Comment by Pavlos1** [comment]
>E907 start...

Means you're looking at the wrong UART. Linux runs on D0 which is a C906 core. The UART for flashing is different from the UART that gives you the Linux console.

**Comment by illantalex** [comment]
Yeah thank you guys, I found another Linux image here that already had the UART port set up for USB [https://wiki.sipeed.com/hardware/en/maix/m1s/other/start.html#Linux-Demo](url) 
But anyway it seems to be pretty useless for real projects because I can't load my own programs to the board's memory (impossible to connect SD card, can't write anything to the SPI flash, only RAM disk where files get erased after rebooting)
